title: SimpleText@CLEF-2024
email: contact@simpletext-project.com
description: >- # this means to ignore newlines until "baseurl:"
        SimpleText is a track organised as part of <a href="https://clef2024.clef-initiative.eu/index.php">CLEF-2024 conference</a>, 
        initiated by <a href="http://www.clef-initiative.eu/">CLEF initiative</a>.
url: "https://simpletext-project.com/2024/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SimpletextW
github_username:  simpletext-madics
